apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: project-a
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: nfs-claim1
          persistentVolumeClaim:
            claimName: nfs-claim1    
      containers:
        - name: httpd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nfs-claim1
              mountPath: /var/www/html
